"""empty message

Revision ID: 375b30921953
Revises: 
Create Date: 2022-07-29 14:14:43.208638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375b30921953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Numeric(), nullable=False),
    sa.Column('qtd_estoque', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('id_filial', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_filial'], ['filial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('qtd_estoque', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deletado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='produtos_pkey')
    )
    op.drop_table('produto')
    op.drop_table('filial')
    # ### end Alembic commands ###
